const express = require('express');
const body_parser = require('body-parser');
const userRouter = require('./routers/user.router');
const parkingRouter = require("./routers/parkingRouter");
const app = express();
app.use(body_parser.json());
app.use('/',userRouter);
app.use('/',parkingRouter);
app.use('/uploads', express.static('uploads'));
module.exports = app;